//
// Created by robcholz on 5/4/24.
//
#pragma once

#ifndef FREERTOS_CPP_WRAPPER_INCLUDE_ATTRIBUTES_HPP
#define FREERTOS_CPP_WRAPPER_INCLUDE_ATTRIBUTES_HPP

#define FREERTOS_ALWAYS_INLINE __attribute__((always_inline))

#endif// FREERTOS_CPP_WRAPPER_INCLUDE_ATTRIBUTES_HPP
